# Generated by Django 5.2.8 on 2025-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='مدرسة الخالدية الابتدائية', max_length=150)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
            ],
        ),
    ]
