# Generated by Django 5.2.8 on 2026-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/logo/', verbose_name='شعار المدرسة'),
        ),
    ]
