# Generated by Django 5.2.8 on 2025-11-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], help_text='اختر اليوم الذي يطبق عليه هذا الجدول.')),
                ('description', models.CharField(default='جدول اليوم', help_text='وصف مختصر للجدول (مثلاً: جدول عادي، جدول اختبار، ...).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل / تعطيل هذا الجدول.')),
            ],
            options={
                'verbose_name': 'جدول يومي',
                'verbose_name_plural': 'الجداول اليومية',
                'unique_together': {('weekday', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='ترتيب الفترة في الجدول (١، ٢، ٣، ...).', verbose_name='الترتيب')),
                ('name', models.CharField(help_text='مثال: الحصة الأولى، بداية الدوام، فسحة...', max_length=100, verbose_name='اسم الفترة')),
                ('type', models.CharField(choices=[('start', 'بداية الدوام'), ('class', 'حصة'), ('break', 'فسحة'), ('end', 'نهاية الدوام'), ('other', 'فترة أخرى')], default='class', max_length=20, verbose_name='النوع')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('class_room', models.CharField(blank=True, help_text='مثال: الصف السادس (أ)', max_length=100, verbose_name='الفصل')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='المعلم')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='المادة')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='display.dayschedule', verbose_name='الجدول اليومي')),
            ],
            options={
                'verbose_name': 'فترة',
                'verbose_name_plural': 'الفترات',
                'ordering': ['order'],
            },
        ),
    ]
