# Generated by Django 5.2.8 on 2025-11-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltimetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المعلم')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرمز (اختياري)')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='من')),
                ('end_time', models.TimeField(verbose_name='إلى')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_slots', to='schooltimetable.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حصة نشاط للمعلم',
                'verbose_name_plural': 'جدول حصص النشاط للمعلمين',
                'ordering': ['day_of_week', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherMainSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='من')),
                ('end_time', models.TimeField(verbose_name='إلى')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_slots', to='schooltimetable.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حصة في الجدول العام',
                'verbose_name_plural': 'الجدول العام للمعلمين',
                'ordering': ['day_of_week', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherWaitingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='من')),
                ('end_time', models.TimeField(verbose_name='إلى')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_slots', to='schooltimetable.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'حصة انتظار للمعلم',
                'verbose_name_plural': 'جدول حصص الانتظار للمعلمين',
                'ordering': ['day_of_week', 'start_time'],
                'abstract': False,
            },
        ),
    ]
