# Generated by Django 5.2.8 on 2025-11-13 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltimetable', '0002_teacher_teacheractivityslot_teachermainslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_day_schedules', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف الجدول'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_day_schedules', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='period',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئت بواسطة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='الترتيب داخل اليوم (1 للحصة الأولى، 2 للثانية، ...).', verbose_name='ترتيب الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('start', 'بداية الدوام'), ('class', 'حصة دراسية'), ('break', 'فسحة / استراحة'), ('end', 'نهاية الدوام')], default='class', max_length=10, verbose_name='نوع الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schooltimetable.dayschedule', verbose_name='الجدول اليومي'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='period',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='period',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_periods', to=settings.AUTH_USER_MODEL, verbose_name='عُدّلت بواسطة'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_days', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='date',
            field=models.DateField(unique=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_days', to='schooltimetable.dayschedule', verbose_name='الجدول المستخدم في هذا اليوم'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان اليوم الخاص'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_special_days', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة'),
        ),
        migrations.AlterField(
            model_name='teacheractivityslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='teachermainslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم'),
        ),
        migrations.AlterField(
            model_name='teacherwaitingslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم'),
        ),
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together={('day_of_week', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('schedule', 'order')},
        ),
        migrations.AddConstraint(
            model_name='teacheractivityslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'start_time', 'end_time'), name='unique_activity_slot_per_teacher_time'),
        ),
        migrations.AddConstraint(
            model_name='teachermainslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'start_time', 'end_time'), name='unique_main_slot_per_teacher_time'),
        ),
        migrations.AddConstraint(
            model_name='teacherwaitingslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'start_time', 'end_time'), name='unique_waiting_slot_per_teacher_time'),
        ),
    ]
