# Generated by Django 5.2.8 on 2025-11-13 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltimetable', '0003_alter_dayschedule_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayschedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dayschedule',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'description'), name='unique_day_schedule_per_description'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('schedule', 'order'), name='unique_period_order_per_schedule'),
        ),
    ]
