# Generated by Django 5.2.8 on 2025-12-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltimetable', '0003_alter_dayschedule_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس')], verbose_name='اليوم')),
                ('period_number', models.PositiveSmallIntegerField(verbose_name='رقم الحصة')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='dayschedule',
            options={'ordering': ['day_of_week', 'id'], 'verbose_name': 'جدول يوم', 'verbose_name_plural': 'جداول الأيام'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['schedule', 'order']},
        ),
        migrations.AlterModelOptions(
            name='specialday',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'معلم', 'verbose_name_plural': 'المعلمين'},
        ),
        migrations.AlterModelOptions(
            name='teacheractivityslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teachermainslot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacherwaitingslot',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teacheractivityslot',
            name='unique_activity_slot_per_teacher_time',
        ),
        migrations.RemoveConstraint(
            model_name='teachermainslot',
            name='unique_main_slot_per_teacher_time',
        ),
        migrations.RemoveConstraint(
            model_name='teacherwaitingslot',
            name='unique_waiting_slot_per_teacher_time',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='dayschedule',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='period',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='period',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='period',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='period',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='title',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المعلم'),
        ),
        migrations.AddField(
            model_name='specialday',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحصة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='ترتيب الحصة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('class', 'حصة دراسية'), ('break', 'فسحة'), ('activity', 'نشاط'), ('other', 'أخرى')], default='class', max_length=20, verbose_name='نوع الفترة'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_days', to='schooltimetable.dayschedule', verbose_name='الجدول الخاص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='رمز المعلم'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المعلم'),
        ),
        migrations.AlterField(
            model_name='teacheractivityslot',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='teacheractivityslot',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='teacheractivityslot',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='teacheractivityslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltimetable.teacher'),
        ),
        migrations.AlterField(
            model_name='teachermainslot',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='teachermainslot',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='teachermainslot',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='teachermainslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltimetable.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherwaitingslot',
            name='end_time',
            field=models.TimeField(verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='teacherwaitingslot',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='teacherwaitingslot',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='teacherwaitingslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltimetable.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytimeslot',
            unique_together={('day_of_week', 'period_number')},
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dayschedule',
            name='updated_by',
        ),
    ]
