# Generated by Django 5.2.8 on 2026-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltimetable', '0004_dailytimeslot_alter_dayschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='صورة المعلم'),
        ),
    ]
